### PR TITLE
Use a task variable to set ansible_python_interpreter

### PR DESCRIPTION
**Pull request by priteau**
In modern Ansible it is now possible to define
ansible_python_interpreter as a task variable. This avoids additional
set_fact tasks, and possible issues such as the one described in this
Kayobe bug: https://storyboard.openstack.org/#!/story/2008284

### CODE REVIEW

**Review by markgoddard — APPROVED** [review]

**Comment by cityofships** [comment]
The role docs and metadata should be updated with what's considered to be a modern Ansible version.

**Comment by priteau** [comment]
> The role docs and metadata should be updated with what's considered to be a modern Ansible version.

Sorry @cityofships, I don't understand. Is this a general comment not related to this particular PR?

**Comment by cityofships** [comment]
Is this a backwards compatible change?

**Comment by cityofships** [comment]
This change broke at least 2 cookiecutter-based project workflows with the following:
```
TASK [stackhpc.os-images : Ensure required packages are installed] *************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "dnf install -y python3-dnf", "msg": "Could not import the dnf python module using /home/centos/actions-runner/_work/smslab-config/smslab-config/ansible/vglab-config-venv/bin/python (3.6.8 (default, Jan 19 2022, 23:28:49) [GCC 8.5.0 20210514 (Red Hat 8.5.0-7)]). Please install `python3-dnf` package or ensure you have specified the correct ansible_python_interpreter.", "rc": 0, "results": [], "stderr": "", "stderr_lines": [], "stdout": "Last metadata expiration check: 4:29:30 ago on Sat 02 Jul 2022 11:34:40 PM UTC.\nPackage python3-dnf-4.7.0-7.el8.noarch is already installed.\nDependencies resolved.\n
```
Downgrade to `v1.13.0` and it works again.

**Comment by priteau** [comment]
Strange, I tested it and didn't notice this issue. I will check again.

**Comment by priteau** [comment]
I wasn't able to replicate, probably because I am running on a host using the release train, so there are no new `python3-dnf` packages available. But I can see how I changed things, so could we test my fix? https://github.com/stackhpc/smslab-config/pull/73

**Pull request merged**
